from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import uuid

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Customer', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('phone',models.CharField(db_index=True,max_length=40)),('email',models.EmailField(blank=True,max_length=254)),('created_at',models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name='Service', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120,verbose_name='Название')),('slug',models.SlugField(unique=True)),('description',models.TextField()),('price_from',models.DecimalField(decimal_places=2,max_digits=10,verbose_name='Цена от')),('duration',models.CharField(blank=True,max_length=80,verbose_name='Срок')),('icon',models.CharField(default='⚙',max_length=8)),('is_active',models.BooleanField(default=True)),('order',models.PositiveIntegerField(default=0))],options={'verbose_name':'Услуга','verbose_name_plural':'Услуги','ordering':['order','name']}),
        migrations.CreateModel(name='SiteSettings', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(default='AUTORA',max_length=100,verbose_name='Название')),('phone',models.CharField(default='+380 44 555 01 20',max_length=40,verbose_name='Телефон')),('address',models.CharField(default='Киев, ул. Промышленная, 18',max_length=200,verbose_name='Адрес')),('telegram',models.URLField(blank=True,verbose_name='Telegram')),('email',models.EmailField(default='service@example.com',max_length=254)),('working_hours',models.CharField(default='Пн–Сб, 08:00–20:00',max_length=100))],options={'verbose_name':'Настройки сайта','verbose_name_plural':'Настройки сайта'}),
        migrations.CreateModel(name='Vehicle', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('make',models.CharField(max_length=80)),('model',models.CharField(max_length=80)),('year',models.PositiveSmallIntegerField(blank=True,null=True)),('plate',models.CharField(blank=True,db_index=True,max_length=20)),('vin',models.CharField(blank=True,max_length=32)),('customer',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='vehicles',to='service.customer'))]),
        migrations.CreateModel(name='Order', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('public_id',models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),('number',models.CharField(blank=True,max_length=20,unique=True)),('problem',models.TextField()),('desired_date',models.DateField()),('desired_time',models.TimeField(blank=True,null=True)),('status',models.CharField(choices=[('new','Новая заявка'),('pending','Ожидает подтверждения'),('booked','Клиент записан'),('accepted','Автомобиль принят'),('diagnostics','Проводится диагностика'),('parts','Ожидаются запчасти'),('repair','Выполняется ремонт'),('ready','Готово к выдаче'),('done','Заказ завершён'),('canceled','Отменён')],db_index=True,default='new',max_length=20)),('estimate',models.DecimalField(blank=True,decimal_places=2,max_digits=10,null=True)),('final_price',models.DecimalField(blank=True,decimal_places=2,max_digits=10,null=True)),('internal_notes',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True,db_index=True)),('updated_at',models.DateTimeField(auto_now=True)),('assigned_to',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='assigned_orders',to=settings.AUTH_USER_MODEL)),('customer',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='orders',to='service.customer')),('service',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='orders',to='service.service')),('vehicle',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='orders',to='service.vehicle'))],options={'ordering':['-created_at']}),
        migrations.CreateModel(name='OrderPhoto', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('image',models.ImageField(upload_to='orders/%Y/%m/',validators=[django.core.validators.FileExtensionValidator(['jpg','jpeg','png','webp'])])),('uploaded_at',models.DateTimeField(auto_now_add=True)),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='photos',to='service.order'))]),
        migrations.CreateModel(name='StatusHistory', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(choices=[('new','Новая заявка'),('pending','Ожидает подтверждения'),('booked','Клиент записан'),('accepted','Автомобиль принят'),('diagnostics','Проводится диагностика'),('parts','Ожидаются запчасти'),('repair','Выполняется ремонт'),('ready','Готово к выдаче'),('done','Заказ завершён'),('canceled','Отменён')],max_length=20)),('message',models.CharField(blank=True,max_length=240)),('created_at',models.DateTimeField(auto_now_add=True)),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='history',to='service.order'))],options={'verbose_name_plural':'История статусов','ordering':['created_at']}),
        migrations.CreateModel(name='OrderComment', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('text',models.TextField()),('created_at',models.DateTimeField(auto_now_add=True)),('author',models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='comments',to='service.order'))],options={'ordering':['-created_at']}),
        migrations.AddIndex(model_name='order',index=models.Index(fields=['status','desired_date'],name='service_ord_status_37c417_idx')),
    ]
