# Generated by Django 5.2.5 on 2026-08-15 23:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_security_outbox_estimates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='service_not_status_a16dc6_idx',
            old_name='service_not_status_next_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='service_not_status_bd7aee_idx',
            old_name='service_not_status_lock_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='service_ord_status_72a3b5_idx',
            old_name='service_ord_status_37c417_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='service_ord_assigne_d06846_idx',
            old_name='service_ord_assigne_58a316_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='service_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_price_from',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='orderphoto',
            name='content_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='orderphoto',
            name='original_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='orderphoto',
            name='size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='Киев', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='service@example.test', max_length=254),
        ),
    ]
