# Generated by Django 5.2.5 on 2026-08-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_service_not_status_next_idx_service_not_status_a16dc6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='⚙', max_length=32),
        ),
    ]
